#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -r ITHACAoutput
#rm -r *.foam
#rm log.*
$WM_PROJECT_DIR/platforms/linux64GccDPInt32Opt/bin/foamListTimes -rm
rm npSnapshots*
rm log
